function(print_base_build_info)
    message(" └─ CCACHE: ${CCACHE_FOUND}")
    message(" └─ CMAKE:")
    message("     └─ VERSION: ${CMAKE_VERSION}")
    message("     └─ HOST: ${CMAKE_HOST_SYSTEM_NAME} ${CMAKE_HOST_SYSTEM_VERSION} ${CMAKE_HOST_SYSTEM_PROCESSOR}")
    message("     └─ TARGET: ${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_VERSION} ${CMAKE_SYSTEM_PROCESSOR}")
    message("     └─ STANDARD:")
    message("         └─ C: ${CMAKE_C_STANDARD}")
    message("         └─ C++: ${CMAKE_CXX_STANDARD}")
    message("     └─ COMPILER:")
    message("         └─ C: ${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION} (${CMAKE_C_COMPILER})")
    message("         └─ C++: ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION} (${CMAKE_CXX_COMPILER})")
    message("     └─ SIMULATE:")
    message("         └─ C: ${CMAKE_C_SIMULATE_ID} ${CMAKE_C_SIMULATE_VERSION}")
    message("         └─ C++: ${CMAKE_CXX_SIMULATE_ID} ${CMAKE_CXX_SIMULATE_VERSION}")
    message("     └─ LINKER: ${CMAKE_LINKER}")
    message("     └─ GENERATOR: ${CMAKE_GENERATOR}")
    message("     └─ MAKE_PROGRAM: ${CMAKE_MAKE_PROGRAM}")
    if(CMAKE_TOOLCHAIN_FILE)
        message("     └─ TOOLCHAIN_FILE: ${CMAKE_TOOLCHAIN_FILE}")
    endif()
    message("     └─ BUILD:")
    message("         └─ TYPE: ${CMAKE_BUILD_TYPE}")
    message("         └─ CROSS_COMPILING: ${CMAKE_CROSSCOMPILING}")
    message("         └─ PARALLEL_LEVEL: ${CMAKE_BUILD_PARALLEL_LEVEL}")
    message("     └─ OUTPUT_DIR:")
    message("         └─ ARCHIVE: ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}")
    message("         └─ LIBRARY: ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
    message("         └─ RUNTIME: ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
    if(APPLE)
        message(" └─ OSX:")
        message("     └─ DEPLOYMENT_TARGET: ${CMAKE_OSX_DEPLOYMENT_TARGET}")
        message("     └─ ARCHITECTURES: ${CMAKE_OSX_ARCHITECTURES}")
    endif()
    if(ANDROID)
        message(" └─ ANDROID:")
        message("     └─ PLATFORM: ${ANDROID_PLATFORM}")
        message("     └─ ABI: ${ANDROID_ABI}")
        message("     └─ NATIVE_API: ${ANDROID_NATIVE_API_LEVEL}")
    endif()
    if(EMSCRIPTEN)
        message(" └─ EMSCRIPTEN:")
        message("     └─ ABI: ${EMSCRIPTEN_SYSTEM_PROCESSOR}")
    endif()
endfunction()

function(dynxx_print_summary TARGET_NAME LINK_LIBS_VAR SANITIZERS_VAR)
    message("")
    message("${TARGET_NAME}")
    print_base_build_info()
    message(" └─ OPTIONS:")
    message("     └─ USE_STD_TO_CHARS: ${USE_STD_TO_CHARS}")
    message("     └─ USE_CURL: ${USE_CURL}")
    message("     └─ USE_LUA: ${USE_LUA}")
    message("     └─ USE_QJS: ${USE_QJS}")
    message("     └─ USE_KV: ${USE_KV}")
    message("     └─ USE_DB: ${USE_DB}")
    message("     └─ USE_DEVICE: ${USE_DEVICE}")
    message("     └─ USE_LIBUV: ${USE_LIBUV}")
    message("     └─ USE_SPDLOG: ${USE_SPDLOG}")
    message("     └─ USE_ADA: ${USE_ADA}")
    message(" └─ LINK_LIBS:")
    foreach(x IN LISTS ${LINK_LIBS_VAR})
        message("     └─ ${x}")
    endforeach()
    message(" └─ SANITIZERS:")
    foreach(x IN LISTS ${SANITIZERS_VAR})
        message("     └─ ${x}")
    endforeach()
    message("")
endfunction()
