name: Base Setup

on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string
      target:
        required: true
        type: string

jobs:
  BuildTools:
    runs-on: ${{ inputs.host == 'macOS' && 'macos-latest' || inputs.host == 'Windows' && 'windows-latest' || 'ubuntu-latest' }}
    steps:
      - name: Setup CMake & Ninja for macOS
        if: inputs.host == 'macOS'
        run: |
          brew install cmake ninja | true

      - name: Setup CMake & Ninja for Linux
        if: inputs.host == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake clang ninja-build

      - name: Setup CMake & Ninja for Windows
        if: inputs.host == 'Windows'
        run: |
          choco install cmake ninja --no-progress --yes
          refreshenv

      - name: Setup msbuild for Windows
        if: inputs.host == 'Windows'
        uses: microsoft/setup-msbuild@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24' 

      - name: Setup tsx
        run: npm install -g tsx

  BuildCache:
    runs-on: ${{ inputs.host == 'macOS' && 'macos-latest' || inputs.host == 'Windows' && 'windows-latest' || 'ubuntu-latest' }}
    steps:
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ inputs.target }}-ccache-${{ runner.os }}
          max-size: 999M
