name: CI for Android on macOS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'third-party/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'build-tools/build-utils.sh'
      - 'build-tools/build-Android.sh'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Cmake
        run: |
          brew install cmake ninja | true

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r29-beta2
          local-cache: true

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
          runVcpkgInstall: false
    
      - name: Build
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
          NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          cd build-tools
          chmod +x build-Android.sh
          ./build-Android.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Android-macOS-build
          path: |
            build.Android/output/
          if-no-files-found: error
