name: CI for Android on macOS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'third-party/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'build-tools/build-utils.sh'
      - 'build-tools/build-Android.sh'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup CMake & Ninja
        run: |
          brew install cmake ninja | true

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Android NDK
        id: cache-ndk
        uses: actions/cache@v4
        with:
          path: ${{ env.ANDROID_HOME }}/ndk/29.0.14206865
          key: android-ndk-29.0.14206865-${{ runner.os }}

      - name: Setup Android NDK
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        uses: android-actions/setup-android@v3
        with:
          packages: 'ndk;29.0.14206865'

      - name: Cache vcpkg binaries
        uses: actions/cache@v4
        with:
          path: ${{ runner.workspace }}/vcpkg-binary-cache
          key: vcpkg-binaries-android-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: false

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: android-ccache-${{ runner.os }}
          max-size: 888M
    
      - name: Build
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
          VCPKG_BINARY_SOURCES: "clear;files,${{ runner.workspace }}/vcpkg-binary-cache,readwrite"
          NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          cd build-tools
          chmod +x build-Android.sh
          ./build-Android.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Android-macOS-build
          path: |
            build.Android/Release/output/
          if-no-files-found: error
