name: CI-Android-Ubuntu

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'test/**'
      - 'platforms/Android/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'tools/utils.ts'
      - 'tools/setup-vcpkg.ts'
      - 'tools/test/gtest-utils.ts'
      - 'tools/build/build-utils.ts'
      - 'tools/build/build-Android.ts'
      - 'tools/routes.ts'
      - 'tools/package.json'
      - '.github/workflows/Base-Setup.yml'
      - '.github/workflows/CI-Android-Ubuntu.yml'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

env:
  ANDROID_NDK_VERSION: 30.0.14904198

jobs:
  baseSetup:
    uses: ./.github/workflows/Base-Setup.yml
    with:
      host: Linux
      target: android

  setupAndroidEnv:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

  build:
    needs: [baseSetup, setupAndroidEnv]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Cache Android NDK
        id: cache-ndk
        uses: actions/cache@v4
        with:
          path: ${{ env.ANDROID_HOME }}/ndk/${{ env.ANDROID_NDK_VERSION }}
          key: android-ndk-${{ env.ANDROID_NDK_VERSION }}-${{ runner.os }}

      - name: Setup Android NDK
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        uses: android-actions/setup-android@v3
        with:
          packages: 'ndk;${{ env.ANDROID_NDK_VERSION }}'

      - name: Setup custom vcpkg
        working-directory: ./tools
        run: |
          npm install
          npm run setup:vcpkg

      - name: Cache vcpkg binary
        id: cache-vcpkg
        uses: actions/cache@v4
        with:
          path: ${{ env.HOME }}/vcpkg-binary-cache
          key: vcpkg-binary-cache-android-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}

      - name: Build
        working-directory: ./tools
        env:
          CI_ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          npm run build:android -- --test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Android-Ubuntu-build
          path: |
            build.Android/Release/output/
          if-no-files-found: error
