name: CI for HarmonyOS on macOS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'third-party/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'build-tools/build-utils.sh'
      - 'build-tools/build-HarmonyOS.sh'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Cmake
      run: |
        brew install cmake ninja | true

    - name: Setup HarmonyOS SDK
      run: |
        curl -L -o ohos-sdk-mac-public.tar.gz "https://mirrors.huaweicloud.com/harmonyos/os/5.1.0-Release/ohos-sdk-mac-public.tar.gz"
        tar -xzf ohos-sdk-mac-public.tar.gz
        cd sdk/packages/ohos-sdk/darwin
        unzip native-darwin-x64-5.1.0.107-Release.zip
        export OHOS_ROOT="${{ github.workspace }}/sdk/packages/ohos-sdk/darwin/native"
        echo "OHOS_ROOT=${{ github.workspace }}/sdk/packages/ohos-sdk/darwin/native" >> $GITHUB_ENV

    - name: Build
      run: |
        cd build-tools
        chmod +x build-HarmonyOS.sh
        ./build-HarmonyOS.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HarmonyOS-build
        path: |
          build.HarmonyOS/Release/output/
        if-no-files-found: error
