name: CI-Linux-Ubuntu

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'test/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'tools/utils.ts'
      - 'tools/test/gtest-utils.ts'
      - 'tools/test/coverage-utils.ts'
      - 'tools/find-llvm.ts'
      - 'tools/setup-vcpkg.ts'
      - 'tools/build/build-utils.ts'
      - 'tools/build/build-Linux.ts'
      - 'tools/routes.ts'
      - 'tools/package.json'
      - '.github/workflows/Base-Setup.yml'
      - '.github/workflows/CI-Linux-Ubuntu.yml'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  baseSetup:
    uses: ./.github/workflows/Base-Setup.yml
    with:
      host: Linux
      target: linux

  build:
    needs: baseSetup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup LLVM and Clang
      run: |
        if ! command -v llvm-cov >/dev/null 2>&1 || ! command -v llvm-profdata >/dev/null 2>&1 || ! command -v clang >/dev/null 2>&1 || ! command -v clang++ >/dev/null 2>&1; then
          sudo apt-get update
          sudo apt-get install -y llvm clang
        fi
        echo "CC=$(command -v clang)" >> "$GITHUB_ENV"
        echo "CXX=$(command -v clang++)" >> "$GITHUB_ENV"

    - name: Setup custom vcpkg
      working-directory: ./tools
      run: |
        npm install
        npm run setup:llvm
        npm run setup:vcpkg

    - name: Cache vcpkg binary
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: ${{ env.HOME }}/vcpkg-binary-cache
        key: vcpkg-binary-cache-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}

    - name: Build
      working-directory: ./tools
      run: |
        npm run build:linux -- --test --coverage

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Linux-Ubuntu-build
        path: |
          build.Linux/Release/output/
        if-no-files-found: error
