name: CI for macOS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'third-party/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'build-tools/build-utils.sh'
      - 'build-tools/build-macOS.sh'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup CMake & Ninja
      run: |
        brew install cmake ninja | true

    - name: Cache vcpkg binaries
      uses: actions/cache@v4
      with:
        path: ${{ runner.workspace }}/vcpkg-binary-cache
        key: vcpkg-binaries-macos-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        runVcpkgInstall: false

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: macos-ccache-${{ runner.os }}
        max-size: 888M

    - name: Build
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg
        VCPKG_BINARY_SOURCES: "clear;files,${{ runner.workspace }}/vcpkg-binary-cache,readwrite"
      run: |
        cd build-tools
        chmod +x build-macOS.sh
        ./build-macOS.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macOS-build
        path: |
          build.macOS/Release/output/
        if-no-files-found: error
