name: CI for macOS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'build-tools/**'
      - 'third-party/**'
      - 'CMakeLists.txt'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Cmake
      run: |
        brew install cmake ninja | true

    - name: Build
      run: |
        cd build-tools
        chmod +x build-macOS.sh
        ./build-macOS.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macOS-build
        path: |
          build.*/output/libs/
          build.*/output/include/
        if-no-files-found: error