name: CI-macOS-Mac

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'test/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'tools/utils.ts'
      - 'tools/test/gtest-utils.ts'
      - 'tools/setup-vcpkg.ts'
      - 'tools/build/build-utils.ts'
      - 'tools/build/build-macOS.ts'
      - 'tools/routes.ts'
      - 'tools/package.json'
      - '.github/workflows/Base-Setup.yml'
      - '.github/workflows/CI-macOS-Mac.yml'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  baseSetup:
    uses: ./.github/workflows/Base-Setup.yml
    with:
      host: macOS
      target: macos

  build:
    needs: baseSetup
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup custom vcpkg
      working-directory: ./tools
      run: |
        npm install
        npm run setup:vcpkg

    - name: Cache vcpkg binary
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: ${{ env.HOME }}/vcpkg-binary-cache
        key: vcpkg-binary-cache-osx-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}

    - name: Build
      working-directory: ./tools
      run: |
        npm run build:macos -- --test

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macOS-Mac-build
        path: |
          build.macOS/Release/output/
        if-no-files-found: error
