name: CI for macOS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'third-party/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'build-tools/build-utils.sh'
      - 'build-tools/build-macOS.sh'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Cmake
      run: |
        brew install cmake ninja | true

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'
        runVcpkgInstall: false

    - name: Build
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      run: |
        cd build-tools
        chmod +x build-macOS.sh
        ./build-macOS.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macOS-build
        path: |
          build.macOS/output/libs/
          build.macOS/output/include/
        if-no-files-found: error
