name: CI-Windows-Win

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'build-tools/utils.ts'
      - 'build-tools/setup-vcpkg.ts'
      - 'build-tools/build-Windows.ts'
      - 'build-tools/routes.ts'
      - 'build-tools/package.json'
      - '.github/workflows/Base-Setup.yml'
      - '.github/workflows/CI-Windows-Win.yml'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  baseSetup:
    uses: ./.github/workflows/Base-Setup.yml
    with:
      host: Windows
      target: windows

  build:
    needs: baseSetup
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup msvc-cmd
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Setup custom vcpkg
        shell: pwsh
        working-directory: ./build-tools
        run: |
          npm install
          npm run setup:vcpkg

      - name: Cache vcpkg binary
        id: cache-vcpkg
        uses: actions/cache@v4
        with:
          path: ${{ env.USERPROFILE }}\vcpkg-binary-cache
          key: vcpkg-binary-cache-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}

      - name: Build
        working-directory: ./build-tools
        run: |
          npm run build:windows

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Win-build
          path: |
            build.Windows/Release/output/
          if-no-files-found: error
