name: CI for WASM on macOS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'third-party/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'build-tools/build-utils.sh'
      - 'build-tools/build-WASM.sh'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  baseSetup:
    uses: ./.github/workflows/Base-Setup.yml
    with:
      host: macOS
      target: wasm

  build:
    needs: baseSetup
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 3.1.65

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        runVcpkgInstall: false

    - name: Cache vcpkg binary
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/vcpkg-binary-cache
        key: vcpkg-binary-cache-wasm-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}

    - name: Build
      env:
        CI_VCPKG_ROOT: ${{ github.workspace }}/vcpkg
        CI_VCPKG_BINARY_SOURCES: "files,${{ github.workspace }}/vcpkg-binary-cache,readwrite"
        CI_EMSCRIPTEN_ROOT: ${{ env.EMSDK }}/upstream/emscripten
      run: |
        cd build-tools
        chmod +x build-WASM.sh
        ./build-WASM.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WASM-build
        path: |
          build.Wasm/Release/output/
        if-no-files-found: error
