name: CI for Windows

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'third-party/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'build-tools/build-utils.sh'
      - 'build-tools/build-Windows.bat'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v2

      - name: Cache vcpkg binaries
        uses: actions/cache@v4
        with:
          path: ${{ runner.workspace }}/vcpkg-binary-cache
          key: vcpkg-binaries-windows-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: false

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: windows-ccache-${{ runner.os }}
          max-size: 888M

      - name: Build
        env:
          VCPKG_ROOT: ${{ github.workspace }}\vcpkg
          VCPKG_BINARY_SOURCES: "clear;files,${{ runner.workspace }}/vcpkg-binary-cache,readwrite"
        run: |
          cd build-tools
          .\build-Windows.bat

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-build
          path: |
            build.Windows/Release/output/
          if-no-files-found: error
