name: CI-WASM-Ubuntu

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'build-tools/utils.ts'
      - 'build-tools/setup-vcpkg.ts'
      - 'build-tools/build-WASM.ts'
      - 'build-tools/routes.ts'
      - 'build-tools/package.json'
      - '.github/workflows/Base-Setup.yml'
      - '.github/workflows/CI-WASM-Ubuntu.yml'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  baseSetup:
    uses: ./.github/workflows/Base-Setup.yml
    with:
      host: Linux
      target: wasm

  build:
    needs: baseSetup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 3.1.65

    - name: Setup custom vcpkg
      working-directory: ./build-tools
      run: |
        npm install
        npm run setup:vcpkg

    - name: Cache vcpkg binary
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: ${{ env.HOME }}/vcpkg-binary-cache
        key: vcpkg-binary-cache-wasm-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}

    - name: Build
      working-directory: ./build-tools
      env:
        CI_WASM_SDK_HOME: ${{ env.EMSDK }}
      run: |
        npm run build:wasm

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WASM-Ubuntu-build
        path: |
          build.Wasm/Release/output/
        if-no-files-found: error
