name: CI for WASM on macOS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'third-party/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'build-tools/build-utils.sh'
      - 'build-tools/build-WebAssembly.sh'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 3.1.65

    - name: Setup Cmake
      run: |
        brew install cmake ninja | true

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'
        runVcpkgInstall: false

    - name: Build
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg
        EMSCRIPTEN_ROOT: ${{ env.EMSDK }}/upstream/emscripten
      run: |
        cd build-tools
        chmod +x build-WebAssembly.sh
        ./build-WebAssembly.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WebAssembly-build
        path: |
          build.Wasm/output/
        if-no-files-found: error
