name: CI for Windows

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'third-party/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'build-tools/build-utils.sh'
      - 'build-tools/build-Windows.bat'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  baseSetup:
    uses: ./.github/workflows/Base-Setup.yml
    with:
      host: Windows
      target: windows

  build:
    needs: baseSetup
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: false

      - name: Cache vcpkg binary
        id: cache-vcpkg
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/vcpkg-binary-cache
          key: vcpkg-binary-cache-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}

      - name: Build
        env:
          CI_VCPKG_ROOT: ${{ github.workspace }}\vcpkg
          CI_VCPKG_BINARY_SOURCES: "files,${{ github.workspace }}/vcpkg-binary-cache,readwrite"
        run: |
          cd build-tools
          .\build-Windows.bat

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-build
          path: |
            build.Windows/Release/output/
          if-no-files-found: error
