name: CI for WASM on macOS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'build-tools/**'
      - 'third-party/**'
      - 'CMakeLists.txt'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 3.1.65

    - name: Setup Cmake
      run: |
        brew install cmake ninja | true

    - name: Build
      env:
        EMSCRIPTEN_ROOT: ${{ env.EMSDK }}/upstream/emscripten
      run: |
        cd build-tools
        chmod +x build-WebAssembly.sh
        ./build-WebAssembly.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WebAssembly-build
        path: |
          build.WebAssembly/output/
        if-no-files-found: error
