name: Deploy-Docs

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/DynXX/**'
      - 'scripts/JS/DynXX.d.ts'
      - 'build-tools/gen-doc.ts'
      - 'build-tools/routes.ts'
      - 'build-tools/package.json'
      - '.github/workflows/Deploy-Docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Generate Docs
        working-directory: ./build-tools
        env:
          DOXYGEN_BIN: /usr/bin/doxygen
        run: |
          npm install
          npm run gen:doc

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build.Docs/site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
