name: Build for iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Dependencies
      run: |
        brew install cmake ninja

    - name: Build
      run: |
        cd build-tools
        chmod +x build-iOS.sh
        ./build-iOS.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: iOS-build
        path: |
          build.iOS/output/libs/
          build.iOS/output/include/
        if-no-files-found: error