name: Lint

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          FILTER_REGEX_INCLUDE: '^(include|src)/.*'
          
          VALIDATE_C: true
          VALIDATE_CPP: true
          VALIDATE_ALL_CODEBASE: false
          
          LOG_LEVEL: INFO
          SUPPRESS_POSSUM: true
