name: Build for Linux on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake clang ninja-build

    - name: Build
      run: |
        cd build-tools
        chmod +x build-Linux.sh
        ./build-Linux.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Linux-build
        path: |
          build.*/output/libs/
          build.*/output/include/
        if-no-files-found: error