name: macOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: write

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        include:
          - os: macos-latest
            script: build-macOS.sh

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Dependencies
      if: runner.os == 'macOS'
      run: |
        brew install cmake ninja

    - name: Build
      run: |
        cd build-tools
        chmod +x ${{ matrix.script }}
        ./${{ matrix.script }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-build
        path: |
          build.*/output/libs/
          build.*/output/include/
        if-no-files-found: error