name: WASM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build

    - name: Build
      env:
        EMSCRIPTEN_ROOT_PATH: ${{ env.EMSDK }}/upstream/emscripten
      run: |
        cd build-tools
        chmod +x build-WebAssembly.sh
        ./build-WebAssembly.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WebAssembly-build
        path: |
          build.WebAssembly/output/
        if-no-files-found: error